name: Build and deploy React app to Azure Web App - folio-client-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies and build
      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build

      # Zip the build folder for deployment
      - name: Zip artifact for deployment
        run: |
          cd client/build
          zip -r ../../../release.zip .

      # Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: client-app

      # Unzip the artifact
      - name: Unzip artifact
        run: |
          unzip release.zip -d wwwroot

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'folio-client-app'
          slot-name: 'Production'
          package: ./wwwroot
